### ISSUE TITLE
catalog-backend-module-gcp: Namespace by project logic inherited to all related entities

### ISSUE THREAD

**Issue by deimantastumas** [backtostage/backstage-plugins#219]
Thank you for adding a possibility to use GCP projects as namespaces for entities! However, I believe this introduced the unexpected outcome.

I will use `CloudSQL` entity as an example. Currently, if `namespaceByProject` is set to true, `CloudSQL` entity gets the correct namespace specified. However, the namespace is also inherited to the owner of this entity. So instead of owner being `TEAM_FOO` I'm getting `NAMESPACE/TEAM_FOO`, which is not expected as my owners are using the `default` namespace.

I couldn't find any documentation about the default behaviour, but I believe that if `owner` is specified without a namespace, the namespace gets inherited from the entity itself. I'm not sure what should be the best way here, as there might be cases where users actually are using namespace-divided ownership. Maybe it would be more correct to explicitly set the namespace of owner to `default` and then allow customisation via Config?

**Comment by angeliski** [comment]
Hey @deimantastumas 

You right about that, a digged in the code base [here](https://github.com/backstage/backstage/blob/master/plugins/catalog-backend/src/processors/BuiltinKindsEntityProcessor.ts#L211) and can see the behaviour is to propagate the namespace and none is provided. I will release a simple fix to always use the default namespace for the owners. 

I will provided a other solution when a more custom approach is necessary to create the Resource entity. Thanks for report

**Comment by angeliski** [comment]
The fix is released :)
